name: localenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - opencv
  - tensorflow
  - keras
  - pip
  - pip:
      - kagglehub